events {
    worker_connections 1024;
}

http {
    upstream fastapi_backend {
        server fastapi:8080;
    }

    server {
        listen 80;
        server_name test-mindmap-chatbot.duckdns.org;
	return 301 https://$server_name$request_uri;
	}

    server{

	listen 443 ssl;
	server_name test-mindmap-chtbot.duckdns.org;

	# SSL certificates
        ssl_certificate /etc/letsencrypt/live/test-mindmap-chtbot.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/test-mindmap-chtbot.duckdns.org/privkey.pem;

        # SSL settings
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        
	location / {
            proxy_pass http://fastapi_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
