"""adding chat log

Revision ID: 01e22a9cf936
Revises: 9884d162d6a5
Create Date: 2025-09-23 02:44:16.854921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e22a9cf936'
down_revision: Union[str, None] = '9884d162d6a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_logs', sa.Column('session_id', sa.String(), nullable=True))
    op.add_column('query_logs', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.add_column('query_logs', sa.Column('chat_logs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'session_id')
    op.drop_column('query_logs', 'chat_id')
    op.drop_column('query_logs', 'chat_logs')

    # ### end Alembic commands ###