"""create query_logs table

Revision ID: b1822018177d
Revises: 
Create Date: 2025-09-16 01:49:13.440486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1822018177d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('query_text', sa.String(), nullable=True),
    sa.Column('used_functions', sa.String(), nullable=True),
    sa.Column('response_length', sa.Integer(), nullable=True),
    sa.Column('mindmap_depth', sa.Integer(), nullable=True),
    sa.Column('error_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_logs')
    # ### end Alembic commands ###
